[package]
name = "png_interlace"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "png_interlace"
path = "src/main.rs"

[dependencies]
image = "0.25"
clap = { version = "4.0", features = ["derive"] }